### ISSUE TITLE
Widths appear to be two characters short

### ISSUE THREAD

**Issue by brendan-r** [rnkn/olivetti#13]
Firstly, thank you for olivetti, it's fantastic!

* I've noticed that the default width of 80 characters actually seems to wrap at 78 for me, for some reason. This could be some interaction with the rest of my config. Even widths seem to be short by 2, odd ones by 3. Can you reproduce?

* Is there a preferred way to set a default width for olivetti in an `init.el` file (e.g. non-interactively)? Even if the width difference is peculiar to my config, I'd like change the default value so that it wraps at 80.

**Comment by rnkn** [comment]
Thanks 😎

I can't reproduce the first issue. Or rather, I can, but I'm not sure it's what you're experiencing. If I insert 80 x's in a buffer with olivetti enabled and a body width of 80 I get this:
~~~
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
x
~~~

The trailing \ takes the place of the 80th x so the line is still 80 characters long. But if I insert x's on the first line here below, it will wrap at column 78 and include the word break.

~~~
Fuga maxime rem amet quod pariatur est hic. Qui totam molestiae quas nisi
saepe. Omnis sint explicabo eligendi porro quidem quia eos qui. Officiis
tempora atque numquam occaecati voluptates placeat. Consequatur consequatur et
et amet sequi illum.
~~~

I think this is more the behaviour of visual line mode. The results are the same if I make a window 80 columns wide with visual line mode turned on. Is this along the lines of what you're experiencing?

For setting the default width, customise or setq `olivetti-body-width`. It can still be overridden per-buffer.

**Comment by brendan-r** [comment]
Hm. Using the `xxx...` example, `visual-line-mode` makes no difference for me in GUI Emacs. I get the same behavior as you (one 'over' in terms of my input, but the correct number of total cols wrapped including the `\`), in a terminal.

As I mainly use the GUI, `olivetti-body-width` to 82 solved my problem. Thanks!
