### ISSUE TITLE
persp-mode interaction: window too small for splitting

### ISSUE THREAD

**Issue by brendan-r** [rnkn/olivetti#14]
Thanks *again* for olivetti!

I'm afraid I've run into what sounds like a recurrence of the _window too small for splitting_ bug referenced in #12, though only when using [`persp-mode`].  If the bug is better reported to the `persp-mode` maintainers, do let me know!

`persp-mode` is part of Spacemacs; it looks like someone else [mentioned the same problem](https://github.com/syl20bnr/spacemacs/issues/7574#issuecomment-258506785) there.

**Context**

`persp-mode` manages 'perspectives'; groups of buffers and window configurations which can be switched between. 

When using a perspective containing vertical splits, and with one or more buffers with `olivetti-mode` mode active, upon navigating away from, and then back to, the perspective, the window configuration is lost, with the error message:

```
[persp-mode] Warning: Can not restore the window configuration, because of the error -- (error Window #<window 3 on  *temp*> too small for splitting)
```
I've tried turning other modes on and off, and this does seem peculiar to `olivetti-mode`.

The problem is slightly different via the GUI and terminal. With the latter, perspectives behave as expected and without error during the session, but a similar error message appears when `persp-mode` attempts to recover the configurations when starting up in a new session.

I'm on GNU Emacs 25.2 on Ubuntu 16.04, using the latest versions of `persp-mode` and `olivetti` from MELPA (20170509.829 and 20160912.1758, respectively).

[`persp-mode`]: https://github.com/Bad-ptr/persp-mode.el

**Comment by rnkn** [comment]
It sounds like `persp-mode` is saving a bunch of window variables, and trying to restore those when the window configuration changes. The problem with that approach is that frequently the same window variables can't be reapplied to a window if it has significantly changed size.

A high-level description of how olivetti works is when that it before a window splits, olivetti removes its own variables, then splits the window as normal. Afterwards, a hook resets its olivetti's environment. (This idea is stolen straight from [`visual-fill-column`](https://github.com/joostkremers/visual-fill-column).) As far as I can tell, this is the only way to get around the changes in Emacs 25 that prompted #12 .

It sounds like `persp-mode` is running into a variation of the same issue. I've had a quick look at the code but it's 3000+ lines and, well, life is finite...

If you can get the developer to chime in with what's happening maybe I can help more.

**Comment by rnkn** [comment]
If the info over at persp-mode helped do you wanna close this issue?

**Comment by brendan-r** [comment]
Yes. Thank you for taking the time to investigate this!
