### ISSUE TITLE
Visual justification

### ISSUE THREAD

**Issue by johnnygroovy** [rnkn/olivetti#15]
Hi !  Great mode ! 
Use it everyday so thanks you :)

Just a little suggestion. I was thinking : would it be possible to get visual justification like [this](https://qph.ec.quoracdn.net/main-qimg-ab36609e40ad471f68324fbf1f7922a3) ?

**Comment by rnkn** [comment]
Hey thanks, glad you get some use out of it.

That is a cool idea but it's really outside the scope of the minor mode. The way lines are wrapped at word boundaries is handled by `visual-line-mode` and if you delve into the code (in `simple.el`) it's actually kinda complex.

Emacs `fill-paragraph` does have an optional argument (i.e. <kbd>C-u M-q</kbd>) to justify fill the paragraph, but this uses hardwrapping, so probably not what you want.

Sorry I can't be more help 😕

**Comment by johnnygroovy** [comment]
Yes I was talking about justification without hardwrapping. Too bad it's so complex to implement, but it was just a cosmetic suggestion, not a real need.

But anyway, thanks for your answer ;)
