### ISSUE TITLE
Olivetti mode errors on enable 

### ISSUE THREAD

**Issue by bronzehedwick** [rnkn/olivetti#16]
I installed Olivetti via MELPA in Aquamacs. I enabled it on a fountain buffer with `M-x olivetti-mode` and I get the following error:

    Wrong type argument: listp, fountain-mode-default 

Any help would be greatly appreciated. Thanks!

**Comment by rnkn** [comment]
The symbol `fountain-mode-default` isn't defined in Fountain mode or Olivetti, so I think something else is creating it. Try `C-h o fountain-mode-default` and see what the first line says.

Then you might like to try starting Emacs with `emacs -Q` (or the equivalent for Aquamacs) and:
~~~
M-x load-file RET path/to/fountain-mode.el RET
M-x load-file RET path/to/olivetti.el RET
~~~

FWIW, the Cocoa build of vanilla GNU Emacs will probably give you a better, more reliable experience than Aquamacs:
~~~
$ brew install emacs --with-cocoa
~~~
or
https://emacsformacosx.com

**Comment by bronzehedwick** [comment]
Got it, thanks!

When I installed vanilla emacs it worked. I'm not sure what was wrong with my Aquamacs setup, but as an emacs beginner I'm sure it was something wonky on my end. Thanks again!
