### ISSUE TITLE
[wishlist] provide configuration example for fullscreen hook

### ISSUE THREAD

**Issue by sten0** [rnkn/olivetti#18]
Hi,

I think Olivetti mode's documentation can be enhanced by adding a code snippet for configuring a custom function that

1) goes full-screen using the newish multiplatform method built into GNU Emacs
2) activating olivetti-mode
3) starting emacs with "emacs -f name-of-this-function"

Such a function can then be trivially bound to a shortcut key such as F11.  An alternate method would be to hook into the fullscreen function, but this has the disadvantage of activating Olivetti when what you're trying to do is work in a full-screen multiwindow Emacs session.

I've been using something like this for many years:
```sh
#!/bin/sh
# jot down an idea
# This program is GPL-2+
# (C) Nicholas D Steeves 2008

/usr/bin/emacs -f custom-jot-function ~/Desktop/Notebook/`date +%y-%m-%d_%R`.txt
```

**Comment by sten0** [comment]
P.S. the idea is to eliminate any thought about the tools and just to write, which I believe is the purpose of Olivetti :-)

**Comment by rnkn** [comment]
The thing is that Olivetti kind of duplicates a subset of the functionality of [writeroom-mode](https://github.com/joostkremers/writeroom-mode), albeit with an approach to keep things buffer-local; the idea being you could have one window set up for coding and one for prose, side-by-side in the same frame. (To a lesser a degree I guess this conflicts a bit with your new description.) So if I went the route of duplicating all/most of the functionality of writeroom-mode, the purpose of which is more in line with your postscript, I feel like it would be stepping on @joostkremers toes.

**Comment by sten0** [comment]
Oh, I totally understand.  Would you please add something to that effect to olivetti's README.md?
