### ISSUE TITLE
Add a screenshot

### ISSUE THREAD

**Issue by jjasghar** [rnkn/olivetti#2]
It would be nice to have a screen shot to explain/show an example.

**Comment by rnkn** [comment]
Good point, I'll pop a couple up showing various configs soon but in the meantime here's one I borrowed from Fountain mode http://files.paulwrankin.com/fountain-mode/screenshot.png

**Comment by jjasghar** [comment]
:D awesome, just thought i should poke about it. :+1:

**Comment by rnkn** [comment]
Fixed in c2b11008912f35ef9d379359115b5bf091670449
