### ISSUE TITLE
Problem with fringe-mode

### ISSUE THREAD

**Issue by egh** [rnkn/olivetti#20]
First of all, thanks for olivetti mode. It makes writing text in emacs feel much more natural.

I have noticed that olivetti mode does not take into account `fringe-mode`.

Steps to reproduce:
1. Start `emacs -q`
2. Install olivetti mode
3. `(fringe-mode 16)`
4. `(olivetti-mode)`

Expected result: 80 columns of characters
Actual result: about 75 columns

See the attached screenshot:
![selection_008](https://user-images.githubusercontent.com/22718/33679785-903932a8-da74-11e7-929d-8b16e34f07fd.png)

**Comment by rnkn** [comment]
Ah, I haven’t used fringe-mode in a long time... Thanks for finding this, I’ll fix soon.

**Comment by rnkn** [comment]
Okay this should do it.

![screen shot 2017-12-07 at 2 53 46 pm](https://user-images.githubusercontent.com/1256849/33699395-b286ae5e-db5e-11e7-9177-d3ba73a11e5d.jpg)

n.b. the 80th column on the window without fringes is of course taken by the continuation character.

**Comment by egh** [comment]
@rnkn Works perfectly! Thank you.
