### ISSUE TITLE
Flashes dark when scrolling

### ISSUE THREAD

**Issue by ianpan870102** [rnkn/olivetti#23]
First of, I really love Olivetti! It helps me concentrate on my work in Org-mode and also keeps the width of the text to a very comfortable readability.
However, I've noticed that when I scroll up and down (particularly with my trackpad) the words would disappear as a whole and leave only my background color for some split second.

p.s. I am using brew-built Emacs 27.0.50 on macOS Mojave

**Comment by xiangsheng** [comment]
Same issue.

**Comment by rnkn** [comment]
Sounds like a change to Emacs display code. Olivetti isn't doing anything but setting the margin sizes.

**Comment by andcarnivorous** [comment]
Similar issue on 25.2.2
When going a page down the margins reset to normal until moving down one line or up two line. This happens both with scroll-mode on and off.
Love the mode btw, I always use it when writing my blog posts.

**Comment by andcarnivorous** [comment]
Sorry, just read the "Known bugs" in the .el file and after switching off linum-mode it works great. Thanks again for the mode!

**Comment by marcelotoledo** [comment]
Recently I've noticed that moving cursor around is extremely laggy and these flashes happens as well. I took a while to identify that the problem only existed when Olivetti was active. Then I decided to read the source code to see how it worked. @rnkn Do you also think that this is an Emacs problem as well?

**Comment by rnkn** [comment]
Sorry for the delay. Just checking this display issue is in GUI Emacs not console?

**Comment by fabrik42** [comment]
Just adding some information: I am facing the same issue in GUI Emacs 26.2, toggling `linum-mode` does not affect the flashing. 

Let me know if I can be of help and thank you for this mode!

**Comment by rnkn** [comment]
I've pushed some changes that remove `post-command-hook`, which could solve this issue, but I can't reproduce it, so if it persists, can someone please report this to bug-gnu-emacs@gnu.org ? Olivetti is in GNU ELPA now, so that's the appropriate place for bug reports.

**Comment by ItsHoff** [comment]
I was suffering from the flickering, but after update the issue seems to be fixed.

**Comment by rnkn** [comment]
Reckon this is resolved for everyone now?
