### ISSUE TITLE
Laggy scrolling

### ISSUE THREAD

**Issue by marcelotoledo** [rnkn/olivetti#26]
Hi! I recently very bothered about Emacs performance moving cursor around and I couldn't identify where the problem was.

Started profiling and turning things on/off until I realized when Olivetti was turned on it made things laggier. 

I couldn't yet identify if it's a GNU Emacs problem or what so I started again isolating stuff around.

I've measured performance simply but using:

(setq-default left-margin-width 70 right-margin-width 70) ; Define new widths.

And it alone makes everything 25% slower.

When testing Olivetti alone it makes 100% slower.

I was wondering if you could help me understand better where exactly the problem is, so I can report it properly to the GNU Emacs bug tracker.

**Comment by rnkn** [comment]
Is this in GUI or terminal?

**Comment by marcelotoledo** [comment]
GUI

**Comment by marcelotoledo** [comment]
I've changed my build and sorted it out.
