### ISSUE TITLE
Conflict with visual-fill-column-mode

### ISSUE THREAD

**Issue by xiangsheng** [rnkn/olivetti#27]
There seems to be some conflicts with visual-fill-column-mode. For example, if both modes are on, the fringes will not move to center as they should do, but remain in edges of the window. Moreover, when using `counsel-M-x`, the visual effect of olivetti mode disappears all the margin setting are restored to the default. It looks that we should turn off the visual-fill-column-mode when entering olivetti mode and restore it when exiting olivetti mode.

Without visual-fill-column-mode
![屏幕快照 2019-03-23 上午12 26 23](https://user-images.githubusercontent.com/5061641/54837915-7766a600-4d02-11e9-8af3-2d4d98d3de37.png)
With visual-fill-column-mode
![屏幕快照 2019-03-23 上午12 26 01](https://user-images.githubusercontent.com/5061641/54837959-8fd6c080-4d02-11e9-8ea7-4d1bd75e1164.png)

**Comment by rnkn** [comment]
This is because olivetti and visual-fill-column-mode attempt to do approximately the same thing. Each will try to set window parameters that will collide with each other. It's really an either/or choice.
