### ISSUE TITLE
"Error during redisplay" whenever I focus out of emacs

### ISSUE THREAD

**Issue by mrbig033** [rnkn/olivetti#29]
#### Runtime Environment

- Manjaro i3 Stable
- GNU Emacs 27.0.50
- olivetti-20190330.1633
- [~/.emacs.d](https://github.com/mrbig033/emacs)
- [use-package declaration](https://github.com/mrbig033/emacs/blob/master/modules/packages/misc/text.org#olivetti):

``` emacs-lisp
(use-package olivetti
  :defer t
  :ensure t
  :config
  (setq-default olivetti-body-width 100)
  (setq olivetti-body-width 100))
```

#### Issue

Whenever I focus out of Emacs, this appears in the Messages buffer:

```
Error during redisplay: (olivetti-set-environment #<window 96 on notes.org>) signaled (wrong-type-argument framep #<window 96 on notes.org>) [4 times]
```

**Comment by rnkn** [comment]
This is a bug in Emacs. The display code has changed to break compatibility for `window-size-change-functions`, a list of functions that was previously passed a frame as argument but now sometimes passes a frame, sometimes a window. Looks like Martin Rudalics broke it from the git blame. Please report to <bug-gnu-emacs@gnu.org>.

**Comment by rnkn** [comment]
This should be fixed on GitHub and GNU ELPA.
