### ISSUE TITLE
Bizzare issue with guide-key mode

### ISSUE THREAD

**Issue by mattly** [rnkn/olivetti#3]
If I have [guide-key mode](https://github.com/kai2nenobu/guide-key) enabled and set to either the right or left position, and I trigger it in olivetti mode, the new guide-key window inherits some of the window padding from the olivetti window, and then I have to close it manually. Sometimes attempting this locks up emacs.

**Comment by rnkn** [comment]
I've found the problem. When the frame is split, `olivetti-set-environment` is trying to return a negative integer for the margin width. Sorry, I'll get a fix out ASAP.

**Comment by rnkn** [comment]
Quick n dirty fix follows. Replace https://github.com/rnkn/olivetti/blob/master/olivetti.el#L162 with....

~~~elisp
(if (< 0 margin)
    (set-window-margins (selected-window) margin margin))))
~~~

Then hit `C-M-x` to take effect.

From my basic testing this seems to solve the major havoc, but I've found that setting `guide-key/popup-window-position` to the right causes problems with window widths. Left, top and bottom seem to work okay. I will keep this issue open for further testing.

**Comment by mattly** [comment]
Thanks for the quick response! I'm still new to emacs and seeing if I can port something similar to my vim writing environment over.
