### ISSUE TITLE
Margins jump around on emacs 27.0.50

### ISSUE THREAD

**Issue by egh** [rnkn/olivetti#30]
I use emacs snapshot on ubuntu 18.04 via https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

```
ii  emacs-snapshot                                        20190505:96967-64f95e4~ubuntu18 amd64                           GNU Emacs editor (with GTK+ user interface)
```

```
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-05-05
````

Recently, the olivetti mode margin has started jumping around.

```
emacs -nw -Q
C-x C-f olivetti.el
M-x eval-buffer
C-x b new-buffer
M-x olivetti-mode
```

Whenever I type, the margin jumps around from the very edges to the standard olivetti margins.

**Comment by rnkn** [comment]
Sounds like it could be a dupe of #29?

**Comment by egh** [comment]
Oops, yes, I didn't see the error message! Thank you.
