### ISSUE TITLE
Bad interaction between `org-special-ctrl-a/e` and olivetti in org-mode

### ISSUE THREAD

**Issue by Zaeph** [rnkn/olivetti#31]
Hello,

I’ve run into a bad interaction between `olivetti` and `org-mode` when the variable `org-special-ctrl-a/e` is set to `t`.

Here’s the docstring for the variable:
```
Non-nil means ‘C-a’ and ‘C-e’ behave specially in headlines and items.

When t, ‘C-a’ will bring back the cursor to the beginning of the
headline text, i.e. after the stars and after a possible TODO
keyword.  In an item, this will be the position after bullet and
check-box, if any.  When the cursor is already at that position,
another ‘C-a’ will bring it to the beginning of the line.

‘C-e’ will jump to the end of the headline, ignoring the presence
of tags in the headline.  A second ‘C-e’ will then jump to the
true end of the line, after any tags.  This also means that, when
this variable is non-nil, ‘C-e’ also will never jump beyond the
end of the heading of a folded section, i.e. not after the
ellipses.

When set to the symbol ‘reversed’, the first ‘C-a’ or ‘C-e’ works
normally, going to the true line boundary first.  Only a directly
following, identical keypress will bring the cursor to the
special positions.

This may also be a cons cell where the behavior for ‘C-a’ and
‘C-e’ is set separately.
```

When it’s set to `t`, enabling `olivetti` in an `org-mode` suppresses the special behaviours and reverts them to their defaults (i.e. `move-end-of-line` & `move-beginning-of-line(-dwim)`).

I had little time to investigate, but I expect the problem to come from some keymap-inheritance from a major-mode.  However, I’ve inspected `olivetti-mode-map`, and there doesn’t seem to be anything out of the ordinary.

HTH.

**Comment by rnkn** [comment]
Sorry I can't think of any way this could be an olivetti bug. I've had a 
look at the relevant org functions but as with most things org, they're 
hideously complex. It might be something to do with the way the org 
functions treat a visual line, but that'd be something they'd have to 
look at.

**Comment by Zaeph** [comment]
Hello again,

You’re absolutely right, this seems to come from org’s `visual-line-mode`, and there’s a thread addressing this issue here:
https://www.mail-archive.com/emacs-orgmode@gnu.org/msg122261.html

Thanks for looking it up and pointing me in the right direction.

**Comment by rnkn** [comment]
Ah cool, thanks for digging into this.

Something that frustrates me a bit about org is that so many functions 
and keybindings become `org-*` variants, which inevitably ends up 
causing problems.

**Comment by Zaeph** [comment]
I’ve had the displeasure of dealing with several of those `org-*` functions for a fairly large patch, and they can surely be frustrating.  It’s even worse with `lispy` (a major-mode for editing lisp).  That being said, I can’t think of an easier way to build on basic commands/functions when you need context-specific behaviours (such as the special `C-a` and `C-e` for `org-mode`).

For those interested in a quick fix, based on [Nicolas Goaziou's explanation](https://www.mail-archive.com/emacs-orgmode@gnu.org/msg122286.html), you can explicitly bind `C-a` and `C-e` to their special behaviours in `org-mode-hook`:
```elisp
(defun org-mode-config ()
  "Modify keymaps used by `org-mode'."
  (local-set-key (kbd "C-a") 'org-beginning-of-line)
  (local-set-key (kbd "C-e") 'org-end-of-line)
  …
  )
(setq org-mode-hook 'org-mode-config)
```

HTH.
