### ISSUE TITLE
One line hint about the fringe for new users 

### ISSUE THREAD

**Issue by sten0** [rnkn/olivetti#33]
It would be nice to have something like this in the docs for new users:
```
;; this will hide the fringe on a per-frame basis, but will not
;; reenable the fringe if olivetti-mode is disabled.
(add-hook 'olivetti-mode-hook (lambda () (set-fringe-style 0)))
```
Of course ideally a call to "fringe-query-style", would be added, storing the value in a buffer-local
variable, which is then restored if olivetti-mode is disabled for a buffer...but that's more work.

[edit: Why?  Because some themes set up the fringe using a contrasting colour, and this is distracting.]

**Comment by rnkn** [comment]
Do you wanna add this to the **Hints** section in the README/Commentary?

**Comment by sten0** [comment]
Sorry for disappearing mid-conversation!  I've been working on a better solution during short bouts of free time.  Please ping me if I seem to be taking too long to submit this work.  Why the change of heart?  I realised that to recommend disabling the fringe may indirectly encourage the proliferation of long lines when composing things that should be hard wrapped (eg: email).

**Comment by sten0** [comment]
Update: oops, I forgot about this project.  Sorry!  'hopefully I'll have enough free time this evening to review and update my work into a solid PR.

**Comment by rnkn** [comment]
I don’t think the fringe-style is really specific to this project though, as in, adding this to any hook will hide the fringes, and it seems pretty well documented on the function and in the manual.

**Comment by sten0** [comment]
"Paul W. Rankin" <notifications@github.com> writes:

> I don’t think the fringe-style is really specific to this project though, as in, adding this to any hook will hide the fringes, and it seems pretty well documented on the function and in the manual.
>

I agree.  The reason for the delay, was that (IIRC) as I was testing the
proposed one-liner and existing documentation I was annoyed that the old
fringe-style wasn't restored when exiting writeroom-mode, so I started
work on a save&set-preference||restore function that would do this.  If
Olivetti isn't the appropriate place for it, then my next best guess
would be `visual-fill-column`--mainly because it has an interesting
side effect; it moves the fringes away from the boundaries of the text
area created by olivetti to the edges of the frame (the left and right
screen edges in full-screen mode).

Failing that, it's a generic-enough convenience thing that upstream
Emacs might also be an option...but not worth creating its own package
for, I think, because it's just a tiny convenience function.

What do you think?

**Comment by rnkn** [comment]
I think writeroom-mode might be the go. The two programs are very similar, except that the main design principle of olivetti is to keep all of its effects buffer-local.

I think it’s worth adding a defcustom olivetti-mode-hook, which I’ll get online in the next few minutes.
