### ISSUE TITLE
set-transient-map is set to nil when running olivetti-expand

### ISSUE THREAD

**Issue by mohkale** [rnkn/olivetti#36]
This is a recent issue, however I've found that when: 

1. I open a buffer.
2. Enable olivetti-mode
3. Run `olivetti-expand` a bunch of times.
4. Run any other command

emacs starts spitting out `set-transient-map PCH: (wrong-type-argument keymapp nil)`. This also has the affect of basically making emacs useless if `toggle-debug-on-error` is true.

**Comment by rnkn** [comment]
Hmm that sound bad. Thanks for reporting. Are you calling `olivetti-expand` with a key or with `M-x`?

**Comment by rnkn** [comment]
Also, can you reproduce by loading Emacs with `emacs -Q` then `M-x load-file RET [PATH TO olivetti.el] RET` then repeating the above?

**Comment by mohkale** [comment]
> Hmm that sound bad. Thanks for reporting. Are you calling olivetti-expand with a key or with M-x?

Key, but I have it bound in my own leader map.

> Also, can you reproduce by loading Emacs with emacs -Q then M-x load-file RET [PATH TO olivetti.el] RET then repeating the above?

Yes, this time I was using `M-x`. I'm on `olivetti-20200207.749` and `GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29`.

**Comment by rnkn** [comment]
I can’t reproduce this, so can you apply this patch and let me know how you go
~~~diff
diff --git a/olivetti.el b/olivetti.el
index 12063f5..0ce43d2 100644
--- a/olivetti.el
+++ b/olivetti.el
@@ -314,7 +314,7 @@ If prefixed with ARG, incrementally decrease."
     (let ((keys (seq-subseq (this-single-command-keys) 0 -1))
           (map (cdr olivetti-mode-map)))
       (seq-do (lambda (k) (setq map (assq k map))) keys)
-      (set-transient-map (cdr map) t))))
+      (when (consp map) (set-transient-map (cdr map) t)))))
 
 (defun olivetti-shrink (&optional arg)
   "Incrementally decrease the value of `olivetti-body-width'.
~~~

**Comment by mohkale** [comment]
Yep, that seems to have fixed it.

Also, now that I have your attention, might I suggest making how many columns olivetti expands by a user option. 2 is almost always too small for me, I'd prefer to make it expand by 4.

**Comment by rnkn** [comment]
Cool. Pushed the change.

Re adding an option for the expansion amount, I doubt it. The transient keymap code allows people to just hammer away at the last key of the binding to get what they want, or press `\` and enter the column specifically. I think that’s enough.

**Comment by mohkale** [comment]
@rnkn I've never been able to get that hammering to work 😢. I'm using emacs evil-mode and so the transient bindings never really activate. It does seem super cool tho, I'll try to get it working.

**Comment by rnkn** [comment]
Yeah I had a look at your config earlier and thought that might be the issue. I suspect that something is using `overriding-terminal-local-map` when it shouldn’t.

**Comment by mohkale** [comment]
Thank you for the assistance, you're correct 😄. It's definitely not an evil-mode issue. In fact, I was looking at the problem wrong. It does work if I use the default bindings I.E. `C-c {` or `C-c }`. It doesn't work if I use a leader-key binding which I suspect is an issue with my own leader package.

I'll fix it when I get a chance, again thank u.

**Comment by Cumol** [comment]
Was this fit already pushed to melpa? Because I just had the same issue

**Comment by rnkn** [comment]
> Was this fit already pushed to melpa? Because I just had the same issue

I don't know what you mean.

**Comment by Cumol** [comment]
I just installed olivetti straight from the github repo and I am getting the same issue.

I am not using the keybinding, but just the `M-x` and `olivetti-expand` multiple times in succession and it leads to that error.

**Comment by rnkn** [comment]
Please attempt to reproduce this with `emacs -Q` and `M-x load-file RET [PATH TO FILE]`

**Comment by Cumol** [comment]
It might be a GUI-specific problem. Doing this in emacs inside a terminal does not have that effect.

I am also doing multiple `C-x C-+ `in the GUI to increase the text size. An option not possible in the terminal emacs.

Starting the gui with `emacs -Q and -l "init.el"` does not show the problem but using `emacs` alone does...

Any idea what this means?

**Comment by rnkn** [comment]
Unfortunately it means the issue is with your init.

**Comment by glptrst** [comment]
Hi,

I have the same problem with Emacs 26.3.

The problem persists without loading my init file (starting emacs with emacs -Q, yanking the content of olivetti.el into the scratch buffer, and evaluating the buffer)

**Comment by rnkn** [comment]
Sorry I can't reproduce this. But I'm on Emacs 27 so that could be something.

Can you please `M-x toggle-debug-on-error` then gist or paste the backtrace (in a code block)?

**Comment by glptrst** [comment]
This is what I got:

`Debugger entered--Lisp error: (wrong-type-argument keymapp nil)`
      `lookup-key(nil [16])`
       `clear-transient-map()`

Where '[16]' changes depending on what key, or key combination, I press. With C-x b, for example, I get:

`Debugger entered--Lisp error: (wrong-type-argument keymapp nil)`
  `lookup-key(nil [24 98])`
  `clear-transient-map()`

**Comment by rnkn** [comment]
That doesn’t look quite right. It should begin (at the bottom) with something like:

    command-execute(olivetti-expand)

**Comment by glptrst** [comment]
I think that's because the error is not triggered by olivetti-expand, but by any command executed after it (as the original post by mohkale says).

However, it seems that I've found the source of the problem. :)

I was executing olivetti-expand with C-x } and then I was repeating the command with C-x z (repeat). After some executions the problem started (with olivetti-shrink as well). I noticed that if I only hit C-x }, then everything seems working fine.

Apologies for having neglected my use of C-x z. Hope this helps.

(Thank you for your package, it's my favorite of the kind)

**Comment by rnkn** [comment]
I see. I’m glad you’ve found a solution. It sounds like you’ve narrowed down a bug, but I still can’t reproduce with the steps I think you’re taking...

Could you do me a favour and detail the exact steps you take to encounter the error? e.g.

1. emacs -Q
2. M-x load-file RET olivetti.el
3. M-x olivetti-mode
4. C-c }
5. C-x z

etc.

**Comment by glptrst** [comment]
1. emacs -Q
2. M-x toggle-debug-on-error
3. M-x load-file RET path/to/olivetti.el
4. M-x olivetti-mode
5. C-c }
6. C-x z
7. z
8. z
`Debugger entered--Lisp error: (wrong-type-argument keymapp nil)`
  `lookup-key(nil [122])`
  `clear-transient-map()`

**Comment by rnkn** [comment]
Thanks. I can’t reproduce this on Emacs 27 so I’ll build 26 and give it a try.

**Comment by rnkn** [comment]
I've managed to reproduce this on Emacs 26. The latest version on MELA (not stable) has a fix that should resolve it. Can you please give this a try when you get a chance?

**Comment by glptrst** [comment]
I confirm. Now the problem is gone. Thank you.
