### ISSUE TITLE
Olivetti does not react to some frame resizing

### ISSUE THREAD

**Issue by nchachereau** [rnkn/olivetti#40]
In some cases, when the Emacs frame is resized, a window where olivetti-mode is enabled is not updated. Evaluating `(olivetti-set-margins)` does not help, so it seems the problem is not with the hook but with the function itself.

I've noticed this in the following situations:

- with [the i3 tiling window manager](https://i3wm.org/), opening an application next to the Emacs frame, so that the space is split in two (this is my own use case);
- in both Gnome and i3, calling `toggle-frame-fullscreen` (bound to F11 by default) twice.

The problem seems to impact Emacs beyond olivetti: for instance elements put on the right of the modeline generated by [doom-modeline](https://github.com/seagle0128/doom-modeline) are hidden after such a resizing. But this also happens with `emacs -Q`, e.g. the scrollbar on the right is hidden.

(My OS is Ubuntu 18.04. Emacs version (`emacs-version`): GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16. Olivetti 1.9.3 (20200320.1154 from Melpa))

**Comment by rnkn** [comment]
Thanks for the report. I've noticed this too (on macOS). I'm quite sure Emacs is at fault here. With each major version, the window display code get broken a little more. I've tried very hard to get the maintainers to stop breaking the window display code but to no avail.

The most obvious pointer is that the margins are being correctly calculated upon entering full screen but not exiting, which is running the same function on the same hook. It's just that Emacs isn't provided the right values for the function to work.

> Evaluating `(olivetti-set-margins)` does not help, so it seems the problem is not with the hook but with the function itself.

This function relies on `window-total-width` returning a correct result, which in this case it doesn't.

Feel free to try get the maintainers to either fix this or swoop in and prove me wrong. Either way is cool.

**Comment by rnkn** [comment]
Actually I have maybe found a workaround. If it's not too much trouble, can you test out the git branch `min-margins`?

**Comment by nchachereau** [comment]
Thanks a lot!

First of all, I tested the `min-margins` branch and it seems to fix the problem for me. However, even though I do not use `text-scale-mode`, I had the idea of trying it out because I saw references to it in your latest commits and in the code, and I get strange error messages with the `min-margins` branch. You might want to look into that before releasing a new version of the package.

Just another note, regarding `window-total-width`: trying the following code in a buffer shows that the function returns a correct result when olivetti-mode is disabled, as well as with the `min-margins` branch:

```elisp
(defun test (&optional win-or-frame)
  (message "%s" (window-total-width)))

(add-hook 'window-size-change-functions #'test t t)
```

However, with master-branch olivetti-mode enabled, the functions then starts reporting erroneous numbers. So it seems master-branch `olivetti-set-margins` somehow fails or changes something that then causes `window-total-width` to fail as well. I just thought I would point this out, because then you can choose between your new branch that you describe as a "workaround" or fixing the older branch.  (Even though I am aware this is maybe not the whole story, because of the way I call the function in my test, ignoring the `win-or-frame` argument.)

Either way, thank you for taking the time and please tell me if I can help with further tests.

**Comment by rnkn** [comment]
Thanks for the investigation. The issue with `text-scale-mode` has been fixed in that branch btw.

I understand that it seems like it should work, but it's not the full story. Olivetti is really just doing the following:
1. resetting the window margins
2. asking for `window-total-width`
3. calculating the window margins based on that

And that's called on `window-size-change-functions` hook.

Which seems simple enough, but resetting the margins *also* calls `window-size-change-functions`. To prevent a loop, Emacs schedules hooks in weird ways. When exiting full screen it's scheduling the hooks incorrectly, or rather just incorrectly to what we want, hence when olivetti asks for `window-total-width` it's receiving the wrong value.

**Comment by nchachereau** [comment]
I see, thanks for the explanation. But mostly many thanks for the update, great to have this fixed! Now I can enjoy writing and taking notes in Emacs with proper margins that adjust when I open other applications :tada:

**Comment by Flinner** [comment]
I still have this issue, how was it fixed?
thanks in advance

**Comment by linwaytin** [comment]
I have the same issue, with i3 window manager on Linux. Maybe it is related to the window manager.
