### ISSUE TITLE
The new keymap appears to still conflict with (or shadow) org-mode's

### ISSUE THREAD

**Issue by sten0** [rnkn/olivetti#47]
Hi,

FYI, the new keymap appears to still conflict with (or shadow) org-mode's, specifically some of the table-related commands:  https://orgmode.org/orgcard.pdf

I'm starting to wonder if it's better to defend against org-mode rather than accommodate it, because org-mode grabs all the good C-c bindings--bindings that are supposed to be reserved for user customisations.  Were I to combine the two I would 1) draft the document.org with stubs 2) disable olivetti mode to access more advanced org-mode functionality  3) or just M-x what I wanted to do.

Add the moment I'm debating overriding the new keymap by-default in the Debian package, rather than forcing users to adapt their habits and configs to a new one that still has issues.  My rationale is that users of org-mode are better equipped to figure this out for themselves than non-users of org-mode, and thus that it's better for Emacs adoption rates to accommodate a new generation of users with [edit: easier] bindings.  For example, what about the following:

C-x C-- and C-x C-= reduce or increase text size.  Would it be more consistent to have olivetti shrink and expand use C-c C-- and C-c C-=?  These do not conflict with or shadow any bindings in org-mode's keymap.

What do you think?

Regards,
Nicholas

**Comment by rnkn** [comment]
I think it's important to separate out the two things you're talking about here. One is the approach to reconciling a collision of key bindings, the other is whether everybody should follow your approach.

I agree that org-mode here is being a bit too greedy in taking up keys, given that the `C-c [punctuation]` is supposedly reserved for minor modes. If you feel strongly about this I encourage you to approach the org-mode maintainers. (Personally I don't use org.)

As for how users ought to deal with key bindings, it's really up to the individual how they choose. As I see it, this championing of individual preference has long been core to everything Emacs. Different people are gonna have different preferences on almost all things, and that's okay.

You're free to adapt the code however you like, I just can't devote time to alternate code-bases (I've previously removed reference to installing via Debian packaging for this very reason).

**Comment by sten0** [comment]
William Rankin <notifications@github.com> writes:

> I think it's important to separate out the two things you're talking about here. One is the approach to reconciling a collision of key bindings, the other is whether everybody should follow your approach.
>

Those are not the two things I am talking about.  The three things are:

1. stable user interface (in the sense of principle of least surprise and not breaking users' habits)
2. defaults that don't conflict with modes that are shipped with every copy of Emacs.
   * https://www.gnu.org/software/emacs/manual/html_node/emacs/Org-Mode.html
3. sensible defaults (arguably subjective)

> I agree that org-mode here is being a bit too greedy in taking up keys, given that the `C-c [punctuation]` is supposedly reserved for minor modes. If you feel strongly about this I encourage you to approach the org-mode maintainers. (Personally I don't use org.)
>

I was impressed with your original defaults :-)  Reverting to `C-[`
satisfies 1 and 3.  Switching to something like `C--` and `C-=`
satisfies 2 and 3.  I took the time to open this issue because at best
`C-{` satisfies 3.  Even without prioritising, that's 2points vs 2points
vs 1point.

The issue is that this change disrupts users' habits and is incompatible
with a mode that is part of Emacs by default.  If compatibility with
upstream Emacs is more important than established user habits then
non-conflicting bindings (ex: `C--` and `C-=`...or use whatever you
prefer) should be used.

Were you to switch to something that satisfies 2 and 3 I would follow
your changes, even if they were unergonomic or difficult, adding a
notification to users at the system package level that the bindings have
changed, plus a hint about overriding keymaps.

> As for how users ought to deal with key bindings, it's really up to the individual how they choose. As I see it, this championing of individual preference has long been core to everything Emacs. Different people are gonna have different preferences on almost all things, and that's okay.
>
> You're free to adapt the code however you like, I just can't devote time to alternate code-bases (I've previously removed reference to installing via Debian packaging for this very reason).

Sorry, I don't understand, are you saying that you're a champion of user
customisation of key bindings, or that you don't support it because it's
an "alternate code-base"?  Or are you talking about how Debian doesn't
have your latest stable release?  If the later, sorry about that, I
didn't have the time and energy to broach the topic of the keymap
regression until now.

You're not expected to dedicate any time to the Debian package, users
using a distribution's package are expected to report bugs to their
distribution's bug tracker, and if they fail to do this an upstream
maintainer will usually close an issue with "use Debian support channels
for Debian packages" or similar.

To be clear, I expect that some users will complain to both our bug
trackers if I import changes that break user habits, and I'm trying to
preempt that.

Of course you can do whatever you want :-)

Cheers,
Nicholas

**Comment by rnkn** [comment]
> You're not expected to dedicate any time to the Debian package, users
> using a distribution's package are expected to report bugs to their
> distribution's bug tracker, and if they fail to do this an upstream
> maintainer will usually close an issue with "use Debian support channels
> for Debian packages" or similar.

Cool. As long as you're covering this then you're free to do whatever you like.
