### ISSUE TITLE
Integration with text-scale-mode

### ISSUE THREAD

**Issue by larstvei** [rnkn/olivetti#5]
Hi!

Right off the bat, I love this piece of Elisp-goodness!

I would like to use this along with `text-scale-mode`, and thought it would be cool to make the window grow dynamically with it. I think it won't be so hard to implement, and I can't see how it would interfere with people who don't use `text-scale-mode`.

I'll fork the repo, and see if I can make it work, and if so, send a pull request. Just thought I'd suggest it here first, in case you have some opinion on the matter!

**Comment by rnkn** [comment]
Thanks, I'm glad you're finding some use in it :)

Do you mean that when calling `text-scale-increase` or `text-scale-decrease` that the margins should dynamically shrink/expand to suit?

Initially I thought just adding `olivetti-set-environment` to `text-scale-mode-hook` would work, but it doesn't...

**Comment by larstvei** [comment]
Hi!

Made the changes now in my fork. In olivetti the width is decided on the basis of characters, but when `text-scale-mode` is enabled, every character a little wider/slimmer. For instance, when pressing `C-x C-+` (assuming `text-scale-mode` was disabled, and you have not done any customization concerning `text-scale-mode`), you'll get text that is scaled by `1.2`. If `olivetti-body-width` is `80`, then you will need `96` as width to compensate for the scaling.

It is perhaps a bit dirty to advice `text-scale-adjust`, but this was the only way I could think of that would allow `olivetti` to be updated dynamically. The main reason that I've added a customizable variable `olivetti-scale-with-text-scale-mode` to enable the feature, is that no advice should be given to the function unless they really want the feature (my impression is that alot of people frown on advises in packages).

For me, this made olivetti way more usable, so I hope you'll include the change!

If there's anything you should be changed in the implementation, let me know!

**Comment by rnkn** [comment]
Yes I definitely think that support for `text-scale-mode` should be included. Thanks for working on this.

I think there may be a cleaner way than advising `text-scale-adjust`. Check out https://github.com/rnkn/olivetti/commit/906974ec6877cfbe4ec3717e0e0f30bb43bc29da and let me know if it works for you?

**Comment by larstvei** [comment]
Yes, using the hook is way better! Just getting the height is also an easier than my approach.

It works beautifully (I also tested with `-q` without problems) as far as I can tell. I hope you merge it into the master branch soon!

**Comment by rnkn** [comment]
Great! Thanks for testing this, and bringing the compatibility issue to my attention in the first place.

The only thing is that I haven't included the `defcustom` you did. I think considering it just gets the `:height` face property and doesn't rely on `text-scale-mode` it shouldn't be a problem... Can you foresee any problems having it hard-coded this way?

**Comment by larstvei** [comment]
I can't. I think it's a great solution!
