### ISSUE TITLE
Unexpected sync between two olivetti-mode windows

### ISSUE THREAD

**Issue by toyboot4e** [rnkn/olivetti#50]
## Bug report

I got this picture. The buffer in the up window is in Olivetti mode (as the mode line suggests), but it lost discraction-free looking (I mean, the width is more than 70):

<img width="864" alt="Screen Shot 2020-07-01 at 23 49 38" src="https://user-images.githubusercontent.com/47905926/86258231-8cb0cc80-bbf5-11ea-89fc-0c4ce732ce5c.png">

## Step to reproduce

First we set Olivetti up opening two files in two windows:

1. `emacs --nw -Q 1.txt 2.txt`
2. M-: `(load "/path/to/olivetti.el")`

We let the two windows, say, A and B, be in `olivetti-mode`:

3. M-x `olivetti-mode`     // window A
4. C-x o (`other-window`)
5. M-x `olivetti-mode`     // window B

Then toggle `olivetti-mode`:

6. M-x `olivetti-mode`     // window B

Now window A lost distraction-free looking while it's in `olivetti-mode`.

### Expected behavior

Window A is in `olivetti-mode` and it keeps distraction-free looking.

## Thank you

I'm really liking Olivetti!

**Comment by rnkn** [comment]
Thanks for reporting this. I've pushed a change. It should be on MELPA in a few hours. Please let me know if this solves the issue for you.

**Comment by toyboot4e** [comment]
Yes it worked. Thank you so much!!
I'm pretty much comfortable. Olivetti is becoming a killer feature for me.
