### ISSUE TITLE
Feature Request: Set Olivetti "gutter" background colour

### ISSUE THREAD

**Issue by aclarknexient** [rnkn/olivetti#54]
Hello,

First off I'd like to say thank you for writing this minor mode, it's really visually pleasing.

Is it possible to set the background colour of the space that Olivetti creates on either side of the document? I looked at the code and didn't see any easy way to add colour, but I'm very much a Lisp novice.

Looking at the image attached to this issue, I'd like to set the colour of the areas surrounded by the red boxes.

![image](https://user-images.githubusercontent.com/69362332/93637691-f7d39900-f9c3-11ea-9cfb-fa307f5c38a6.png)

If it's not possible without some major work, please delete this. I don't want to cause any hassle!

**Comment by rnkn** [comment]
You're welcome. So Olivetti only controls the Emacs margins, and unfortunately Emacs doesn't provide a margin face, it just takes the default face. It would be nice, but as far as I can figure, not possible.
