### ISSUE TITLE
Middle mouse click does not paste

### ISSUE THREAD

**Issue by A6GibKm** [rnkn/olivetti#55]
When doing middle-click on top of the margins I get
```
<left-margin> <mouse-2> is undefined
```
Originally, middle click anywhere on the screen should paste the contents of the clipboard on the cursor position.

**Comment by rnkn** [comment]
You can't paste in the Emacs margins.

**Comment by A6GibKm** [comment]
You mean the margins of the graphic toolkit? that makes sense. In any case, in olivetti mode I cant paste on the left or right margin introduced by olivetti mode, which are quite big, ~50% of the horizontal space. I can't find any margin on emacs without it.
