### ISSUE TITLE
Side window bug

### ISSUE THREAD

**Issue by suconakh** [rnkn/olivetti#61]
# Summary
There is a strange bug happening when I try to use `window-toggle-side-windows` inside a side window when the other window has `olivetti-mode` enabled. At first, it works just fine, side window being hidden. But when I try to show it back, something strange happens and the main window becomes a side window (it can't be split), and the previous side window buffer opens in the main window instead of on the side. I am not sure how to debug it but i managed to find a reproducible way to cause this bug

# Steps to reproduce
## Minimal configuration
```emacs-lisp
;; bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; install olivetti
(straight-use-package 'olivetti)

;; display help buffers in side window
(setq display-buffer-alist
      '(("\\*Help.*"
         (display-buffer-in-side-window))))
```
## Inside emacs
`M-x olivetti-mode RET` Enable olivetti mode
`C-h f + RET` Open any help buffer
`C-x o` Switch to it
`M-x window-toggle-side-windows` Toggle side window
`M-x window-toggle-side-windows` Toggle it back

Now `window-toggle-side-windows` doesn't work at all and emacs' behaviour of displaying buffers is broken until `olivetti-mode` is turned off

# System
- Emacs 29.0.50
- PGTK
- Native comp

**Comment by rnkn** [comment]
For bugs, please ensure you can reproduce with:

    $ emacs -Q -l olivetti.el

**Comment by rnkn** [comment]
I've reproduced an error, but I'm not sure if it's the same error because it's with `emacs -Q` on master branch.

Would you mind terribly if we resolved this over email? For some reason Github issues make me grumpy. Email is pwr@bydasein.com

**Comment by suconakh** [comment]
Sure!
