### ISSUE TITLE
Olivetti errors on org buffer

### ISSUE THREAD

**Issue by artelse** [rnkn/olivetti#64]
When I enable `olivetti-mode` in a text scratch buffer it centers the text fine. However in an org buffer it errors and does nothing: 
`Error during redisplay: (olivetti-set-window #<window 15 on 20220109T003018-electronics.org>) signaled (wrong-type-argument number-or-marker-p unspecified)`

Backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p unspecified)
  olivetti-scale-width(648)
  olivetti-normalize-width(72 #<window 15 on 20220109T003018-electronics.org>)
  olivetti-set-window(#<window 15 on 20220109T003018-electronics.org>)
  olivetti-set-buffer-windows()
  olivetti-mode(toggle)
  funcall-interactively(olivetti-mode toggle)
  command-execute(olivetti-mode record)
  execute-extended-command(nil "olivetti-mode" nil)
  funcall-interactively(execute-extended-command nil "olivetti-mode" nil)
  command-execute(execute-extended-command)
```

**Comment by rnkn** [comment]
I'm having trouble reproducing this in Emacs on console. Are you using graphical Emacs?

Also is this reproducible by starting Emacs with `emacs -Q` as per the instructions?

**Comment by artelse** [comment]
I cannot reproduce with `emacs -Q`, so something is conflicting in my configuration. If I find the culprit will report back for future reference.

**Comment by rnkn** [comment]
Thanks.

**Comment by artelse** [comment]
Been probing around in my config and found that `mixed-pitch-mode` is causing the error. When I remove `mixed-pitch-mode` it just works as expected. Now am wondering, if this is a `olivetti` problem?

**Comment by artelse** [comment]
Ok, this seems an old bug described [here](https://gitlab.com/jabranham/mixed-pitch/-/issues/7) with a pull request [here](https://github.com/rnkn/olivetti/pull/25).
When I run the code in the PR description, `olivetti` works normally.

**Comment by rnkn** [comment]
I had a look at mixed-pitch-mode but not sure I understand the reason for it; what’s it doing differently to just setting custom faces?

If memory serves, olivetti calculates based on the default face so there shouldn’t be a problem with having mixed face sizes in a buffer.

**Comment by artelse** [comment]
In the linked PR, Nielius talks about a problem with the calculation of height. However, when I set `mixed-pitch-set-height` to `nil` olivetti works.`mixed-pitch` is used widely because of convenience setting the various faces needing fixed space.
