### ISSUE TITLE
olivetti-mode isn't activated on the minibuffer when executing isearch commands.

### ISSUE THREAD

**Issue by templateK** [rnkn/olivetti#66]
It seems there are two possible candidate hooks for enabling `olivetti-mode` on the minibuffer when executing isearch.
`minibuffer-setup-hook` or `isearch-mode-hook` 

## minibuffer-setup-hook
It looks like isearch is activating minibuffer but it's not. We can see that by observing `minibuffer-setup-hook` 
 isn't triggered by `isearch-forward`until we explicitly focus on the minibuffer.

## isearch-mode-hook
Since isearch commands won't change focus to minibuffer, `olivetti-mode` won't be activated on minibuffer.
So, we have to get the minibuffer object and activate `olivetti-mode` with it. 

```elisp
(defun olivetti-isearch-mode-setup ()
  (let* ((win (minibuffer-window))
         (buf (window-buffer win)))
    (with-current-buffer buf
      (olivetti-mode 1))))

(add-hook 'isearch-mode-hook 'olivetti-isearch-mode-setup)
```

This should work but it won't. My guess is that the hooks `olivetti-mode` relies on isn't firing. 

A hack to go around this issue is calling `olivetti-set-window` explicitly after enabling `olivetti-mode` on minibuffer.

```elisp
(defun olivetti-isearch-mode-setup ()
  (let* ((win (minibuffer-window))
         (buf (window-buffer win)))
    (with-current-buffer buf
      (olivetti-mode 1)
      (olivetti-set-window win))))

(add-hook 'isearch-mode-hook 'olivetti-isearch-mode-setup)

**Comment by rnkn** [comment]
Emacs minor modes do not apply to the minibuffer.

**Comment by templateK** [comment]
@rnkn Oh, I didn't I know that.  Just for clarification, The functionality (centering text) works on minibuffer is not a intended feature of this package, Right?

**Comment by rnkn** [comment]
Correct. The minibuffer is its own distinct buffer.

**Comment by shaohme** [comment]
> [@rnkn](https://github.com/rnkn) Oh, I didn't I know that. Just for clarification, The functionality (centering text) works on minibuffer is not a intended feature of this package, Right?

Did you find another way to center minibuffer text, or add padding/margins to it?

**Comment by templateK** [comment]
Enabling `olivetti-mode` on the minibuffer through `mini-buffer-setup-hook` works fine "enough" for me.

I don't know whether this method will work on the latest version because I'm using `2.0.4`.
Anyway, here's my `use-package` code for olivetti.

```elisp
(use-package olivetti
  :init
  (defmacro foo/olivetti-mode-on (width)
    `(lambda ()
       (setq-local olivetti-body-width ,width)
       (olivetti-mode 1)))
  :config
  (add-hook 'minibuffer-setup-hook  (foo/olivetti-mode-on 120) -100 nil)
 )
```

**Comment by shaohme** [comment]
This works on my setup too 😄 , but only seems to trigger first when a mode loads `olivetti-mode`. After this, minibuffer is consistently padded afterward. I use `use-package` in my config too so maybe there is a delay.

Although, it seems to break after usage 😦 When invoking the minibuffer I momentarily see the buffer with padding for 0.2 second after which it expands again. Perhaps I have got something in my hooks that tampers with olivetti-mode?
