### ISSUE TITLE
feature request: maintain a minimum left margin

### ISSUE THREAD

**Issue by tbdcit** [rnkn/olivetti#72]
It would be very nice to be able to always maintain a small left margin between the body text and the window divider, even when the window is very narrow. 

One way to do this is to set `olivetti-body-width` to something like `0.9` and `olivetti-minimum-body-width` to something very small. However, when the window is large the body text is also too wide. 

It would be nice if there was also a `olivetti-maximum-body-width` setting, or some other way to make sure there is always a bit of margin around the body text.

**Comment by larstvei** [comment]
Have you tried adding an internal border width to your frame? I have this in my config, and I am wondering if this is maybe what you are after (though I know it doesn't fully address your question):

```emacs-lisp

(add-to-list 'default-frame-alist '(internal-border-width . 24))

```

Perhaps you also want to check out how to customize [window dividers](https://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Dividers.html)?

We could also consider making olivetti preserve whatever window margin or fringe is set (right now it seems to override it); that way it would you could set a default margin (perhaps on the olivetti-mode-hook). This might be better behavior overall.

It would be great to hear a bit more about your use case, to understand wether this is a feature that *should* be a part of olivetti, or if there are simple customizations that would work just as well.

**Comment by tbdcit** [comment]
Thank you! Setting `window-divider-default-right-width` to the same size as the internal border and enabling `window-divider-mode` solved my issue, making sure that there is a consistent margin around the text even when the frame size is small.
