### ISSUE TITLE
Echo area messages when width changed non-interactively

### ISSUE THREAD

**Issue by butter-radish** [rnkn/olivetti#75]
When called from Lisp, can `(olivetti-set-width)` not post a message in the echo area? I have a function to automatically set a different Olivetti width in my Dired buffers, and it’s annoying to get the “text width has been set” message every time I move directories.

I think there are ways to suppress messages to the echo area, but I’m reporting this as an issue because I don’t think any message should be sent if body width is changed non-interactively.

**Comment by rnkn** [comment]
That’s an interactive command so shouldn’t be called from lisp. Try this instead:

```elisp
(setq olivetti-body-width WIDTH)
(olivetti-set-buffer-windows)
```

**Comment by butter-radish** [comment]
Ohhh.

Thank you so much 😅💙
