### ISSUE TITLE
Feature request: Add setting for (nots, enabling `visual-line-mode` when olivetti is toggled

### ISSUE THREAD

**Issue by rappie** [rnkn/olivetti#76]
By default Olivetti enables visual line mode. This seems sensible for most cases.

In `prog-mode` I prefer to have `truncate-lines` enabled and `visual-line-mode` disabled. It would be nice to have a setting for this.

I've tried using a hook like this:
```elisp
    (defun rappie/disable-visual-line-mode ()
        (message "rappie/disable-visual-line-mode")
        (visual-line-mode -1)
    )
    (add-hook 'olivetti-mode-hook 'rappie/disable-visual-line-mode)
```
This doesn't work. The message gets printed but visual line mode is still enabled. I'm an elisp novice so please let me know if i'm doing something wrong here :slightly_smiling_face: 

I finally got it working with this:
```elisp
  (defun rappie/disable-visual-line-mode (&rest args)
    "Disable visual-line-mode."
    (visual-line-mode -1))

  (advice-add 'olivetti-mode :after #'rappie/disable-visual-line-mode)
```

**Comment by rnkn** [comment]
I must admit I've never quite understood the pairing of Olivetti with programming modes; from the beginning its design was aimed at prose, and so pretty tightly tied to `visual-line-mode`. I'd probably like to keep it this way. Doing one thing well and all that.

You could try `olivetti-mode-on-hook` which might be cleaner than the hook that is run at both enable and disable.

**Comment by rappie** [comment]
I like to have the code centered in the buffer, for all modes :slightly_smiling_face: 

I also use https://github.com/trevorpogue/topspace

Thanks for your suggestion. I will give it a try.

**Comment by larstvei** [comment]
The solution to remove visual-line-mode on `oliveti-mode-on-hook` should work. I used to have this is my config and never ran into any problems:

```emacs-lisp
(remove-hook 'olivetti-mode-on-hook 'visual-line-mode)
```

I'll assume that this is a solution, and close the issue.

**Comment by rnkn** [comment]
Oh of course, I forgot we did this. Thanks @larstvei
