### ISSUE TITLE
Don't enable olivetti mode when window too narrow

### ISSUE THREAD

**Issue by iliakur** [rnkn/olivetti#77]
Thanks for your package! I use it every day.

Right now I enable it for certain modes, but I noticed that if I'm using my vertical screen I don't really need olivetti-mode.

Do you think it would be easy to check the window/frame width before enabling it?

**Comment by rnkn** [comment]
Hi. This is what Olivetti does. It's very minimal code, essentially just a hook when the window changes; if the window is too narrow it does nothing.

**Comment by iliakur** [comment]
Nice! How can I control what's considered "too narrow"? I have `olivetti-body-width` set to 103, but I think I'd like to disable it when window body width is already around 150.

**Comment by rnkn** [comment]
You can't. Too narrow is just when `olivetti-body-width` exceeds the window width.

**Comment by iliakur** [comment]
Gotcha, so I'll try to implement something custom
