### ISSUE TITLE
Scaled titles in org mode

### ISSUE THREAD

**Issue by SlobDad** [rnkn/olivetti#85]
When Org heading faces are scaled up and have tags, the lines are broken.

Reproduce with:

`
(set-face-attribute 'org-level-1 nil :height 1.3 :underline t)
`

Then open a Org buffer with a heading that has tags.

edit: I figured out that tweaking org-tags-column variable can fix this.

**Comment by rnkn** [comment]
This is just the lines wrapping. You need to change `org-tags-column`.
