### ISSUE TITLE
The fraction of the body is changing with text-scale-mode

### ISSUE THREAD

**Issue by linwaytin** [rnkn/olivetti#86]
From the README, I thought if `olivette-body-width` is set to a fraction, like 0.8, then the ratio of body width to the window width will be fixed to 0.8, by changing the text wrapping in the body. In my case, I saw the ratio is changing when I use `text-scale-increase(decrease)`. Is this a bug on my system, or I just misunderstand the description of the feature?

Thank you.

**Comment by rnkn** [comment]
I see what you mean. The text should really scale within a 0.8 width of the window, rather than scale the width and text together like it does with an integer. I’ll have a look into it. Should be an easy fix.

**Comment by linwaytin** [comment]
I got a simple workaround as follows:
```elisp
  (defun my-reset-olivetti-width ()
    "Reset the appearance when text-scale-mode is used."
    (interactive)
    (olivetti-set-width (/ (default-value 'olivetti-body-width)
			   (expt text-scale-mode-step
				 text-scale-mode-amount)
			   )
			)
    )
  (add-hook 'text-scale-mode-hook #'my-reset-olivetti-width)
```

This function checks the current text scale level and changes the `olivette-body-width` accordingly.
This has the drawback that it always turns back to the default value of `olivette-body-width`. A fix in the package's code should be better.

**Comment by linwaytin** [comment]
This is a better version, adding a conditional to check if `olivette-mode` is on in the buffer.
```elisp
  (defun my-reset-olivetti-width ()
    "Reset the appearance when text-scale-mode is used."
    (interactive)
    (if olivetti-mode
	(olivetti-set-width (/ (default-value 'olivetti-body-width)
			       (expt text-scale-mode-step
				     text-scale-mode-amount))
			    )
      )
    )
  (add-hook 'text-scale-mode-hook #'my-reset-olivetti-width)
```

**Comment by rnkn** [comment]
It's much easier than that: e3ced654f0cdc335e263183bf7737642df3eedba

Should be on MELPA soon. Let me know if you have any problems.

**Comment by linwaytin** [comment]
Yeah, that works better! Thanks a lot.
