### ISSUE TITLE
How to get the real width of window

### ISSUE THREAD

**Issue by not-null-nil** [rnkn/olivetti#87]
Hi, dear developers.

When using with [popwin](https://github.com/emacsorphanage/popwin), popwin need to use the width of window, by  `(window-width root-win)`, which olivetti mode will change.
For example, while the true value of the window is 120, it may reduce it to 82.

As a result, when using something like
```
(push '(" *undo-tree*" :width 0.3 :position right) popwin:special-display-config)
```

popwin get the wrong width, and the popwin window is too large than it should be.

Is it possible to get the real width of window?

I have open an issue here, too. https://github.com/emacsorphanage/popwin/issues/151

**Comment by rnkn** [comment]
If I understand correctly you want the width of the window plus fringes and margins, in columns? You can get this with:

```
(/ (window-pixel-width) (frame-char-width))
```

**Comment by not-null-nil** [comment]
Yes, it works perfectly for me, great thanks!
